---
title: "HW 4.1"
author: "Ben Wilson"
date: "5/26/2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

# Question

Describe a situation or problem from your job, everyday life, current events, etc., for which a clustering model would be appropriate. List some (up to 5) predictors that you might use.
s
# Responseas

Customer segmentation is the typical business example use case for clustering. I actually applied a k-means clustering algorithm at my job. It recieved great feedback, has been in production for nearly 2 years now. 

Clustering is best when you know there should be groups, but are unsure where to draw the lines between them. Said another way, you do not have a target variable to train a classifier on.

The predictors do not need to be complex. I took all of our customers and the number of users/agents they had for each of our four products. 

Scaling was key to getting a good result due to the large difference in ranges between products that sold user by user (typically 1 to 25 users) and by agents (25 to 10,000 end-points).

The other variable I played tweaked frequently during exploration was the number of clusters. There is no guide for the number of clusters, so I had to review by hand each group and see if they made *intuitive* sense. I settled on 11 customer segments, which allowed us to identify cross-sell opportunities and identify different needs for our customers after follow-up research.

**In-Brief**  
Customer Segmentation is a good use for clustering.  
The features I used were:  

- Product 1 Users
- Product 2 Users
- Product 3 Agents
- Product 4 Agents